name: Update promo URL manually

on:
  workflow_dispatch:
    inputs:
      new_url:
        description: 'Nueva URL promocional'
        required: true
        type: string

jobs:
  update-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Reemplazar URL en archivo
        run: |
          echo "Reemplazando todas las URLs promocionales en index.html..."

          NEW_URL="${{ inputs.new_url }}"

          awk -v new_url="$NEW_URL" '
            {
              gsub(/https:\/\/www\.udemy\.com\/course\/derecho-presupuestario-orientado-a-oposiciones\/\?couponCode=[A-Za-z0-9]+/, new_url)
              print
            }
          ' index.html > index.tmp && mv index.tmp index.html

          echo "Todas las URLs actualizadas correctamente."

      - name: Commit y push si hay cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Actualizar URL promocional"
          git push
