name: Update promo URL manually

on:
  workflow_dispatch:
    inputs:
      new_url:
        description: 'Nueva URL promocional'
        required: true
        type: string

jobs:
  update-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Reemplazar URL en archivo
        run: |
          echo "Reemplazando todas las URLs promocionales en index.html..."

          NEW_URL="${{ inputs.new_url }}"
          ESCAPED_NEW_URL=$(printf '%s\n' "$NEW_URL" | sed 's/[&@]/\\&/g')

          sed -i "s@https://www\.udemy\.com/course/derecho-presupuestario-orientado-a-oposiciones/\?couponCode=[^\"']*@${ESCAPED_NEW_URL}@g" index.html

          echo "Todas las URLs actualizadas correctamente."

      - name: Commit y push si hay cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Actualizar URL promocional"
          git push
