name: Update promo URL manually

on:
  workflow_dispatch:
    inputs:
      new_url:
        description: 'Nueva URL promocional'
        required: true
        type: string

jobs:
  update-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Reemplazar URL en archivo
        run: |
          echo "Buscando URL anterior en index.html..."

          OLD_URL=$(grep -oE 'https://www\.udemy\.com/course/derecho-presupuestario-orientado-a-oposiciones/\?couponCode=[^"]+' index.html || true)

          echo "OLD_URL encontrado: $OLD_URL"
          NEW_URL="${{ inputs.new_url }}"

          if [ -n "$OLD_URL" ]; then
            ESCAPED_OLD_URL=$(printf '%s\n' "$OLD_URL" | sed -e 's/[\/&|]/\\&/g')
            ESCAPED_NEW_URL=$(printf '%s\n' "$NEW_URL" | sed -e 's/[\/&|]/\\&/g')
            sed -i "s|$ESCAPED_OLD_URL|$ESCAPED_NEW_URL|g" index.html
            echo "URL actualizada correctamente."
          else
            echo "No se encontró una URL anterior con el patrón esperado."
            exit 1
          fi

      - name: Commit y push si hay cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Actualizar URL promocional"
          git push
